### PR TITLE
miscellaneous cleanups

### PR DESCRIPTION
**Pull request by froydnj**
I'm still working through the process of understanding the code and how it relates to the modifications to Firefox you've already made.  As part of that, it seemed reasonable to fix up a few things in the code, and to make some notes for potential problems.  Feel free to reject anything in here!

### CODE REVIEW

**Comment by froydnj** [comment]
Rebased to current master and fixed up the tests so they actually work without NaCl available.

**Comment by shravanrn** [comment]
Sorry, I totally missed this PR earlier. Looking at it now and will merge it in with my changes in the next day or 2

**Comment by shravanrn** [comment]
So I have cherry picked the commits with some modifications and tested after rebasing. Some comments below

Cast cleanup/forwarding - This is definitely one part of the code that needs some cleanup. I have merged the cast cleanups as is - but there is definitely more cleanup needed here. I will look into it when I get the chance.

Forwarding - i want to be a little careful here before enabling use of std::forward, as I want to make sure that eliding copies doesn't compromise "sandboxing security". Let me think about this a bit more and we can revisit it. For the moment, this should not be an issue, aside from small overhead as the libraries used are C libraries, and so the APIs do not have features like reference parameters which need forwarding for "correct usage of the API"

Multiplication Overflow- Good point - the multiplication could overflow if the size of a type is 2^32 or more. Unlikely but best to check. Added a static_assert

No NaCl - I have also added some flags in the makefile so you can exclude nacl and or wasm in the test app

Let me know if you have any thoughts. (Also - Github sometimes fails to notify me, so if you see lack of response in 2 days, feel free to ping me)

**Comment by froydnj** [comment]
Thanks for merging these!  Just one question:

> Forwarding - i want to be a little careful here before enabling use of std::forward, as I want to make sure that eliding copies doesn't compromise "sandboxing security". Let me think about this a bit more and we can revisit it. For the moment, this should not be an issue, aside from small overhead as the libraries used are C libraries, and so the APIs do not have features like reference parameters which need forwarding for "correct usage of the API"

I can understand the desire to be careful here, but I also think that relying on not-apparent-at-the-call-site copying semantics to ensure sandbox security is somewhat sketchy.  Can you elaborate on what you think would be a problematic case?

> Multiplication Overflow- Good point - the multiplication could overflow if the size of a type is 2^32 or more. Unlikely but best to check. Added a static_assert

Thanks for looking at this.  I don't think the code you added works properly for 32-bit platforms, though.  It also doesn't address:

https://github.com/shravanrn/rlbox_api/pull/1/commits/23402c84ecf9be649e55a63cd74702891ee2fdce#diff-73aff2a68ddd18a4724c82c2a4c3b9c2R1394

**Pull request closed without merging**
